INSERT INTO MY_USER_DETAILS
(ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ENABLED, ID, PASSWORD, ROLES, USERNAME)
VALUES (TRUE, TRUE, TRUE, TRUE, 2, '$2a$12$XhKiZyufS8j4XOqwhB6AqOHD0FciakYJVr4e1NiozbtE4Q2Is2jvG', 'USER', 'Palak');
